/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edunova.view;

import edunova.model.Grupa;
import edunova.model.Polaznik;
import java.awt.Toolkit;
import java.util.Properties;
import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import net.atlanticbb.tantlinger.shef.HTMLEditorPane;

/**
 *
 * @author Edunova
 */
public class SlanjePoruke extends javax.swing.JFrame {

    private Grupa grupa;
    private Polaznik odabrano;
    private HTMLEditorPane editor;

    /**
     * Creates new form SlanjePoruke
     */
    public SlanjePoruke(Grupa g) {
        initComponents();
        setIcon();
        setLocationRelativeTo(null);
        setTitle("E-mail");
        grupa = g;

        DefaultListModel<Polaznik> m = new DefaultListModel<>();
        for (Polaznik p : grupa.getPolaznici()) {
            m.addElement(p);
        }

        primatelji.setModel(m);

        editor = new HTMLEditorPane();
        editor.setSize(editorKontejner.getSize());
        editorKontejner.add(editor);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        naslov = new javax.swing.JTextField();
        akcijaPosalji = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        primatelji = new javax.swing.JList();
        jLabel2 = new javax.swing.JLabel();
        editorKontejner = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Naslov");

        akcijaPosalji.setIcon(new javax.swing.ImageIcon(getClass().getResource("/slike/mail-send.png"))); // NOI18N
        akcijaPosalji.setText("Pošalji");
        akcijaPosalji.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                akcijaPosaljiActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(primatelji);

        jLabel2.setText("Primatelji");

        javax.swing.GroupLayout editorKontejnerLayout = new javax.swing.GroupLayout(editorKontejner);
        editorKontejner.setLayout(editorKontejnerLayout);
        editorKontejnerLayout.setHorizontalGroup(
            editorKontejnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        editorKontejnerLayout.setVerticalGroup(
            editorKontejnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/slike/Cancel.png"))); // NOI18N
        jButton1.setText("Odustani");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(naslov, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(18, 18, 18)
                                .addComponent(akcijaPosalji, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(editorKontejner, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(naslov, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(5, 5, 5)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                    .addComponent(editorKontejner, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(akcijaPosalji)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void akcijaPosaljiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_akcijaPosaljiActionPerformed

        // Sender's email ID needs to be mentioned
        String from = "nekretnine121@gmail.com";
        String pass = "edunovaj14";
        // Recipient's email ID needs to be mentioned.

        String host = "smtp.gmail.com";

        // Get system properties
        Properties properties = System.getProperties();
        // Setup mail server
        properties.put("mail.smtp.starttls.enable", "true");
        properties.put("mail.smtp.host", host);
        properties.put("mail.smtp.user", from);
        properties.put("mail.smtp.password", pass);
        properties.put("mail.smtp.port", "587");
        properties.put("mail.smtp.auth", "true");

        // Get the default Session object.
        Session session = Session.getDefaultInstance(properties);
        
        odabrano = (Polaznik) primatelji.getSelectedValue();
        
        if (odabrano == null) {
            JOptionPane.showMessageDialog(rootPane, "Prvo odaberite kome želite slati poruku", "Pogreška", JOptionPane.ERROR_MESSAGE);
            this.primatelji.requestFocus();
            return;
        }

        try {
            // Create a default MimeMessage object.
            MimeMessage message = new MimeMessage(session);

            // Set From: header field of the header.
            message.setFrom(new InternetAddress(from));

            // Set To: header field of the header.
            for (Polaznik p : grupa.getPolaznici()) {
                if (p.getEmail() == null || p.getEmail().trim().length() == 0) {
                    continue;
                }
                message.addRecipient(Message.RecipientType.TO,
                        new InternetAddress(p.getEmail()));
            }

            // Set Subject: header field
            message.setSubject(naslov.getText());

            // Now set the actual message
            message.setText(editor.getText(), "utf-8", "html");

            // Send message
            
            
            
            Transport transport = session.getTransport("smtp");
            transport.connect(host, from, pass);
            transport.sendMessage(message, message.getAllRecipients());
            transport.close();
            System.out.println("Poruka uspješno poslana....");
        } catch (MessagingException mex) {
            mex.printStackTrace();
        }
        dispose();
    }//GEN-LAST:event_akcijaPosaljiActionPerformed
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/slike/edunova_icon.png")));
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton akcijaPosalji;
    private javax.swing.JPanel editorKontejner;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField naslov;
    private javax.swing.JList primatelji;
    // End of variables declaration//GEN-END:variables
}
