/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package edunova.view;

import edunova.controller.ObradaAgent;
import edunova.model.Agent;
import edunova.utility.Pomocno;
import java.awt.Color;
import java.awt.Component;
import java.awt.Toolkit;
import java.util.Arrays;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

public class Agenti extends javax.swing.JFrame {
    
    private ObradaAgent obradaAgent;
    private Agent odabrano;

    /**
     * Creates new form Agenti
     */
    public Agenti() {
        initComponents();
        setIcon();
        obradaAgent = new ObradaAgent();
        setLocationRelativeTo(null);
        lista.setModel(new DefaultListModel<Agent>());
        setTitle("Agenti: "
                + Pomocno.getAgent().getImePrezime());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        uvjet = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        akcijaTrazi = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lista = new javax.swing.JList();
        jLabel2 = new javax.swing.JLabel();
        korisnik = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        lozinka = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        lozinkaPonovo = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        ime = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        prezime = new javax.swing.JTextField();
        akcijaOdustani = new javax.swing.JButton();
        akcijaDodajNovi = new javax.swing.JButton();
        akcijaPromjeni = new javax.swing.JButton();
        akcijaObrisi = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        oib = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        brojtelefona = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Uvjet (* za sve)");

        akcijaTrazi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/Magnifier2.png"))); // NOI18N
        akcijaTrazi.setText("Traži");
        akcijaTrazi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                akcijaTraziActionPerformed(evt);
            }
        });

        lista.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listaValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lista);

        jLabel2.setText("Korisničko ime");

        jLabel3.setText("Lozinka");

        jLabel4.setText("Lozinka ponovo");

        jLabel5.setText("Ime");

        jLabel6.setText("Prezime");

        akcijaOdustani.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/Cancel__Red.png"))); // NOI18N
        akcijaOdustani.setText("Odustani");
        akcijaOdustani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                akcijaOdustaniActionPerformed(evt);
            }
        });

        akcijaDodajNovi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/Plus__Orange.png"))); // NOI18N
        akcijaDodajNovi.setText("Dodaj novi");
        akcijaDodajNovi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                akcijaDodajNoviActionPerformed(evt);
            }
        });

        akcijaPromjeni.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/Pencil3.png"))); // NOI18N
        akcijaPromjeni.setText("Promjeni");
        akcijaPromjeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                akcijaPromjeniActionPerformed(evt);
            }
        });

        akcijaObrisi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/DeleteRed.png"))); // NOI18N
        akcijaObrisi.setText("Obriši");
        akcijaObrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                akcijaObrisiActionPerformed(evt);
            }
        });

        jLabel7.setText("OIB");

        jLabel8.setText("Broj telefona");

        jLabel9.setText("e-mail");

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/real_estate_picture.jpg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(akcijaOdustani, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(akcijaDodajNovi, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(akcijaPromjeni, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(akcijaObrisi, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(uvjet)
                        .addGap(18, 18, 18)
                        .addComponent(akcijaTrazi))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(lozinka, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(korisnik, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lozinkaPonovo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel7)
                            .addComponent(oib)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(prezime)
                            .addComponent(jLabel8)
                            .addComponent(brojtelefona)
                            .addComponent(jLabel9)
                            .addComponent(email)
                            .addComponent(ime, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(13, 13, 13))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(uvjet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(akcijaTrazi))))
                        .addGap(23, 23, 23)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(prezime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(oib, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(korisnik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lozinka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lozinkaPonovo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(brojtelefona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(akcijaOdustani)
                    .addComponent(akcijaDodajNovi)
                    .addComponent(akcijaPromjeni)
                    .addComponent(akcijaObrisi))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void akcijaTraziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_akcijaTraziActionPerformed
        
        cistiPolja();
        
        List<Agent> agenti = obradaAgent.
                dohvati(uvjet.getText());
        
        DefaultListModel<Agent> m = new DefaultListModel<>();
        for (Agent agent : agenti) {
            m.addElement(agent);
        }
        lista.setModel(m);
        
    }//GEN-LAST:event_akcijaTraziActionPerformed

    private void listaValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listaValueChanged
        reset();
        odabrano = (Agent) lista.getSelectedValue();
        if (odabrano == null) {
            return;
        }
        korisnik.setText(odabrano.getKorisnik());
        lozinka.setText("");
        lozinkaPonovo.setText("");
        ime.setText(odabrano.getIme());
        prezime.setText(odabrano.getPrezime());
        oib.setText(odabrano.getOib());
        brojtelefona.setText(String.valueOf(odabrano.getBrojtelefona()));
        email.setText(odabrano.getEmail());
        
    }//GEN-LAST:event_listaValueChanged

    private void akcijaOdustaniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_akcijaOdustaniActionPerformed
        dispose();
    }//GEN-LAST:event_akcijaOdustaniActionPerformed

    private void akcijaDodajNoviActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_akcijaDodajNoviActionPerformed
        reset();
        if (korisnik.getText().trim().isEmpty()) {
            greska(korisnik, "Obavezno korisnik");
            return;
        }
        
        if (!obradaAgent.provjeraKorisnika(korisnik.getText().trim())) {
            greska(korisnik, "Korisnik postoji u bazi, odabarite drugi");
            return;
        }
        
        if ((new String(lozinka.getPassword())).trim().isEmpty()) {
            greska(lozinka, "Obavezno lozinka");
            return;
        }
        if ((new String(lozinkaPonovo.getPassword())).trim().isEmpty()) {
            greska(lozinkaPonovo, "Obavezno ponovo lozinka");
            return;
        }
        
        if (!Arrays.equals(lozinka.getPassword(), lozinkaPonovo.getPassword())) {
            greska(lozinka, "Lozinke ne odgovaraju");
            greska(lozinkaPonovo, "Lozinke ne odgovaraju");
            return;
        }
        
        if (ime.getText().trim().isEmpty()) {
            greska(ime, "Obavezno ime");
            return;
        }
        if (prezime.getText().trim().isEmpty()) {
            greska(prezime, "Obavezno prezime");
            return;
        }
        
        if (oib.getText().trim().isEmpty()) {
            greska(oib, "Obavezno OIB");
            return;
        }
        
        if (brojtelefona.getText().trim().isEmpty()) {
            greska(brojtelefona, "Obavezno broj telefona");
            return;
        }
        
        if (email.getText().trim().isEmpty()) {
            greska(email, "Obavezno e-mail");
            return;
        }
        
        Agent o = new Agent();
        o.setKorisnik(korisnik.getText().trim());
        o.setLozinka(new String(lozinka.getPassword()));
        o.setIme(ime.getText().trim());
        o.setPrezime(prezime.getText().trim());
        o.setOib(oib.getText().trim());
        o.setBrojtelefona(brojtelefona.getText().trim());
        o.setEmail(email.getText().trim());
        
        o = obradaAgent.dodaj(o);
        
        DefaultListModel<Agent> m = (DefaultListModel<Agent>) lista.getModel();
        m.addElement(o);

       

    }//GEN-LAST:event_akcijaDodajNoviActionPerformed
    
    private void greska(JComponent komponenta, String obavijest) {
        komponenta.setBackground(Color.red);
        komponenta.requestFocus();
        komponenta.setToolTipText(obavijest);
        
    }
    
    private void reset() {
        
        for (Component c : this.getContentPane().getComponents()) {
            if (c instanceof JTextField || c instanceof JPasswordField) {
                JComponent jc = (JComponent) c;
                jc.setBackground(Color.white);
                jc.setToolTipText("");
            }
        }
    }
    
    private void cistiPolja() {
        korisnik.setText("");
        lozinka.setText("");
        lozinkaPonovo.setText("");
        ime.setText("");
        prezime.setText("");
        oib.setText("");
        brojtelefona.setText("");
        email.setText("");
    }
    
    
    private void akcijaPromjeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_akcijaPromjeniActionPerformed
        if (odabrano == null) {
            return;
        }        
        reset();
        
        if (!odabrano.getKorisnik().equals(korisnik.getText().trim())) {
            if (!obradaAgent.provjeraKorisnika(korisnik.getText().trim())) {
                greska(korisnik, "Korisnik postoji, odaberite drugo korisničko ime");
                return;
            }
            
        }
        if (new String(lozinka.getPassword()).trim().length() > 0
                && new String(lozinkaPonovo.getPassword()).trim().length() > 0
                && !Arrays.equals(lozinka.getPassword(), lozinkaPonovo.getPassword())) {
            greska(lozinka, "Lozinka i lozinka ponovo ne odgovaraju");
            greska(lozinkaPonovo, "Lozinka i lozinka ponovo ne odgovaraju");
        }
        
        if (ime.getText().trim().isEmpty()) {
            greska(ime, "Obavezno ime");
            return;
        }
        if (prezime.getText().trim().isEmpty()) {
            greska(prezime, "Obavezno prezime");
            return;
        }
        if (oib.getText().trim().isEmpty()) {
            greska(oib, "Obavezno OIB");
            return;
        }
        if (brojtelefona.getText().trim().isEmpty()) {
            greska(brojtelefona, "Obavezno broj telefona");
            return;
        }
        if (email.getText().trim().isEmpty()) {
            greska(email, "Obavezno e-mail");
            return;
        }
        
        odabrano.setKorisnik(korisnik.getText().trim());
        odabrano.setLozinka(new String(lozinka.getPassword()));
        odabrano.setIme(ime.getText());
        odabrano.setPrezime(prezime.getText());
        odabrano.setOib(oib.getText());
        odabrano.setBrojtelefona(brojtelefona.getText());
        odabrano.setEmail(email.getText());
        
        if (!obradaAgent.promjeni(odabrano)) {
            return;
        }
        
        lista.repaint();
        
    }//GEN-LAST:event_akcijaPromjeniActionPerformed

    private void akcijaObrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_akcijaObrisiActionPerformed
        
        odabrano = (Agent) lista.getSelectedValue();
        if (odabrano == null) {
            return;
        }
        
        if(odabrano.getSifra()==Pomocno.getAgent().getSifra()){
            JOptionPane.showMessageDialog(getParent(), "Nije moguće trenutno brisati: " + odabrano.getImePrezime(), "Upozorenje!", WIDTH);
        return;
        }
            
        
        if (JOptionPane.showConfirmDialog(getParent(), "Jeste li sigurni da želite obrisati: " + odabrano.getImePrezime() + "?", "Brisanje agenta", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE) == JOptionPane.NO_OPTION) {
            return;
        }
        
        if (!obradaAgent.obrisi(odabrano)) {
            return;
        }
        
        DefaultListModel<Agent> m = (DefaultListModel<Agent>) lista.getModel();
        m.removeElement(odabrano);
        lista.repaint();
        cistiPolja();
    }//GEN-LAST:event_akcijaObrisiActionPerformed

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/pictures/real_estate_icon.jpg")));
    }
    
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton akcijaDodajNovi;
    private javax.swing.JButton akcijaObrisi;
    private javax.swing.JButton akcijaOdustani;
    private javax.swing.JButton akcijaPromjeni;
    private javax.swing.JButton akcijaTrazi;
    private javax.swing.JTextField brojtelefona;
    private javax.swing.JTextField email;
    private javax.swing.JTextField ime;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField korisnik;
    private javax.swing.JList lista;
    private javax.swing.JPasswordField lozinka;
    private javax.swing.JPasswordField lozinkaPonovo;
    private javax.swing.JTextField oib;
    private javax.swing.JTextField prezime;
    private javax.swing.JTextField uvjet;
    // End of variables declaration//GEN-END:variables

}
