/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edunova.view;

import edunova.utility.Pomocno;
import java.awt.Toolkit;
import java.text.SimpleDateFormat;
import java.util.Date;

/**
 *
 * @author Mario
 */
public class Izbornik extends javax.swing.JFrame {

    /**
     * Creates new form Izbornik
     */
    public Izbornik() {
        initComponents();
        setLocationRelativeTo(null);
        setIcon();
        setTitle("NEKRETNINE v1.0:  " + 
               Pomocno.getAgent().getImePrezime());
        
       SimpleDateFormat df = new SimpleDateFormat(Pomocno.FORMAT_DATUM);
       datum.setText(df.format(new Date()));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        akcijaAgenti = new javax.swing.JButton();
        AkcijaNekretnine = new javax.swing.JButton();
        AkcijaKlijenti = new javax.swing.JButton();
        AkcijaPonudaPotraznja = new javax.swing.JButton();
        AkcijaOdjava = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();
        datum = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setForeground(java.awt.Color.white);
        setIconImages(null);

        akcijaAgenti.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/Agent-Male-Light-icon.png"))); // NOI18N
        akcijaAgenti.setText("Agenti");
        akcijaAgenti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                akcijaAgentiActionPerformed(evt);
            }
        });

        AkcijaNekretnine.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/kde_user_home.png"))); // NOI18N
        AkcijaNekretnine.setText(" Nekretnine");
        AkcijaNekretnine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AkcijaNekretnineActionPerformed(evt);
            }
        });

        AkcijaKlijenti.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/Clients-icon.png"))); // NOI18N
        AkcijaKlijenti.setText(" Klijenti");
        AkcijaKlijenti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AkcijaKlijentiActionPerformed(evt);
            }
        });

        AkcijaPonudaPotraznja.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/kde_folder_saved_search.png"))); // NOI18N
        AkcijaPonudaPotraznja.setText("Ponuda/potražnja");
        AkcijaPonudaPotraznja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AkcijaPonudaPotraznjaActionPerformed(evt);
            }
        });

        AkcijaOdjava.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/logout.png"))); // NOI18N
        AkcijaOdjava.setText(" Odjava");
        AkcijaOdjava.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AkcijaOdjavaActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/real_estate_background.jpg"))); // NOI18N

        jToolBar1.setRollover(true);
        jToolBar1.add(datum);

        jMenu1.setText("Datoteka");

        jMenuItem1.setText("Izlaz");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Pomoć");

        jMenuItem2.setText("O programu");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(akcijaAgenti)
                        .addGap(18, 18, 18)
                        .addComponent(AkcijaKlijenti)
                        .addGap(18, 18, 18)
                        .addComponent(AkcijaNekretnine)
                        .addGap(18, 18, 18)
                        .addComponent(AkcijaPonudaPotraznja)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(AkcijaOdjava)))
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(akcijaAgenti)
                        .addComponent(AkcijaKlijenti)
                        .addComponent(AkcijaNekretnine)
                        .addComponent(AkcijaPonudaPotraznja))
                    .addComponent(AkcijaOdjava))
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 390, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        new Oprogramu().setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void akcijaAgentiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_akcijaAgentiActionPerformed
        new Agenti().setVisible(true);
    }//GEN-LAST:event_akcijaAgentiActionPerformed

    private void AkcijaNekretnineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AkcijaNekretnineActionPerformed
        new Nekretnine().setVisible(true);
    }//GEN-LAST:event_AkcijaNekretnineActionPerformed

    private void AkcijaKlijentiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AkcijaKlijentiActionPerformed
        new Klijenti().setVisible(true);
    }//GEN-LAST:event_AkcijaKlijentiActionPerformed

    private void AkcijaPonudaPotraznjaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AkcijaPonudaPotraznjaActionPerformed
        new PonudePotraznje().setVisible(true);
    }//GEN-LAST:event_AkcijaPonudaPotraznjaActionPerformed

    private void AkcijaOdjavaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AkcijaOdjavaActionPerformed
        dispose();
        new Autorizacija().setVisible(true);
    }//GEN-LAST:event_AkcijaOdjavaActionPerformed

    
    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/pictures/real_estate_icon.jpg")));
    }
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AkcijaKlijenti;
    private javax.swing.JButton AkcijaNekretnine;
    private javax.swing.JButton AkcijaOdjava;
    private javax.swing.JButton AkcijaPonudaPotraznja;
    private javax.swing.JButton akcijaAgenti;
    private javax.swing.JLabel datum;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables

    
}
