/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edunova.view;

import edunova.model.Nekretnina;
import edunova.model.SlikaNekretnine;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.DefaultListModel;
import org.imgscalr.Scalr;

/**
 *
 * @author Mario
 */
public class PreglednikSlika extends javax.swing.JFrame {

    private Nekretnina odabrano;

    /**
     * Creates new form PreglednikSlika
     */
    public PreglednikSlika(Nekretnina odabrano) {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Preglednik slika");
        setIcon();
        this.odabrano=odabrano;
        preglednik.setCellRenderer(new StavkaListeSlika());
        ucitajSliku();

    }

    
    private void ucitajSliku() {

        File folder = new File("pictures" + File.separator + "pictures_nekretnine" + File.separator);

        BufferedImage slikaSdiska;
        DefaultListModel<SlikaNekretnine> m = new DefaultListModel<>();
        SlikaNekretnine s;
        for (final File fileEntry : folder.listFiles()) {
            if (fileEntry.isDirectory()) {
                continue;
            }
            if (!fileEntry.getName().split("_")[0].equals(String.valueOf(odabrano.getSifra()))) {
                continue;
            }
            try {
                slikaSdiska = ImageIO.read(fileEntry);
                s = new SlikaNekretnine();
                s.setSlika(Scalr.resize(slikaSdiska, Scalr.Method.QUALITY, Scalr.Mode.AUTOMATIC,
                        600, 600, Scalr.OP_ANTIALIAS));
                s.setPutanja(fileEntry.getAbsolutePath());
                m.addElement(s);
            } catch (IOException ex) {
                Logger.getLogger(Nekretnine.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

        preglednik.setModel(m);

    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        preglednik = new javax.swing.JList();
        akcijaOdustani = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        preglednik.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                preglednikValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(preglednik);

        akcijaOdustani.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/Cancel__Red.png"))); // NOI18N
        akcijaOdustani.setText("Odustani");
        akcijaOdustani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                akcijaOdustaniActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(akcijaOdustani)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(akcijaOdustani)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void preglednikValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_preglednikValueChanged
        SlikaNekretnine s = (SlikaNekretnine) preglednik.getSelectedValue();
        if (s == null) {
            return;
        }
        
       ucitajSliku();
    }//GEN-LAST:event_preglednikValueChanged

    private void akcijaOdustaniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_akcijaOdustaniActionPerformed
        dispose();
    }//GEN-LAST:event_akcijaOdustaniActionPerformed

    
    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/pictures/real_estate_icon.jpg")));
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton akcijaOdustani;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList preglednik;
    // End of variables declaration//GEN-END:variables
}
