/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edunova.view;

import edunova.utility.Pomocno;
import java.awt.Toolkit;
import java.beans.PropertyVetoException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Mario
 */
public class Izbornik extends javax.swing.JFrame {

    /**
     * Creates new form Izbornik
     */
    public Izbornik() {
        initComponents();
        setLocationRelativeTo(null);
        setIcon();
        setTitle("NEKRETNINE v1.1:  " + 
               Pomocno.getAgent().getImePrezime());
        
       SimpleDateFormat df = new SimpleDateFormat(Pomocno.FORMAT_DATUM);
       datum.setText(df.format(new Date()));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        AkcijaPonudaPotraznja = new javax.swing.JButton();
        AkcijaNekretnine = new javax.swing.JButton();
        AkcijaKlijenti = new javax.swing.JButton();
        akcijaAgenti = new javax.swing.JButton();
        AkcijaOdjava = new javax.swing.JButton();
        jToolBar1 = new javax.swing.JToolBar();
        datum = new javax.swing.JLabel();
        pozadina = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        akcijaIzlaz = new javax.swing.JMenuItem();
        oProgramu = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setForeground(java.awt.Color.white);
        setIconImages(null);
        setSize(new java.awt.Dimension(1000, 600));
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jDesktopPane1.setBackground(new java.awt.Color(102, 153, 255));

        AkcijaPonudaPotraznja.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/kde_folder_saved_search.png"))); // NOI18N
        AkcijaPonudaPotraznja.setText("Ponude");
        AkcijaPonudaPotraznja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AkcijaPonudaPotraznjaActionPerformed(evt);
            }
        });

        AkcijaNekretnine.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/kde_user_home.png"))); // NOI18N
        AkcijaNekretnine.setText(" Nekretnine");
        AkcijaNekretnine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AkcijaNekretnineActionPerformed(evt);
            }
        });

        AkcijaKlijenti.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/Clients-icon.png"))); // NOI18N
        AkcijaKlijenti.setText(" Klijenti");
        AkcijaKlijenti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AkcijaKlijentiActionPerformed(evt);
            }
        });

        akcijaAgenti.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/Agent-Male-Light-icon.png"))); // NOI18N
        akcijaAgenti.setText("Agenti");
        akcijaAgenti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                akcijaAgentiActionPerformed(evt);
            }
        });

        AkcijaOdjava.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/logout.png"))); // NOI18N
        AkcijaOdjava.setText(" Odjava");
        AkcijaOdjava.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AkcijaOdjavaActionPerformed(evt);
            }
        });

        jToolBar1.setRollover(true);
        jToolBar1.add(datum);

        pozadina.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/1685471.png"))); // NOI18N

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(akcijaAgenti, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AkcijaKlijenti, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AkcijaPonudaPotraznja, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AkcijaOdjava, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AkcijaNekretnine, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pozadina, javax.swing.GroupLayout.PREFERRED_SIZE, 900, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addComponent(akcijaAgenti)
                        .addGap(35, 35, 35)
                        .addComponent(AkcijaKlijenti)
                        .addGap(36, 36, 36)
                        .addComponent(AkcijaNekretnine)
                        .addGap(35, 35, 35)
                        .addComponent(AkcijaPonudaPotraznja)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(AkcijaOdjava))
                    .addComponent(pozadina, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jDesktopPane1.setLayer(AkcijaPonudaPotraznja, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(AkcijaNekretnine, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(AkcijaKlijenti, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(akcijaAgenti, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(AkcijaOdjava, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jToolBar1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(pozadina, javax.swing.JLayeredPane.DEFAULT_LAYER);

        getContentPane().add(jDesktopPane1);

        jMenu1.setText("Datoteka");

        akcijaIzlaz.setText("Izlaz");
        akcijaIzlaz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                akcijaIzlazActionPerformed(evt);
            }
        });
        jMenu1.add(akcijaIzlaz);

        jMenuBar1.add(jMenu1);

        oProgramu.setText("Pomoć");

        jMenuItem2.setText("O programu");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        oProgramu.add(jMenuItem2);

        jMenuBar1.add(oProgramu);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void akcijaIzlazActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_akcijaIzlazActionPerformed
        System.exit(0);
    }//GEN-LAST:event_akcijaIzlazActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        new Oprogramu().setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void akcijaAgentiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_akcijaAgentiActionPerformed
        Agenti agenti = new Agenti();
        jDesktopPane1.add(agenti);
        try {
            agenti.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(Izbornik.class.getName()).log(Level.SEVERE, null, ex);
        }
        agenti.show();
    }//GEN-LAST:event_akcijaAgentiActionPerformed

    private void AkcijaNekretnineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AkcijaNekretnineActionPerformed
        Nekretnine nekretnine = new Nekretnine();
        jDesktopPane1.add(nekretnine);
        try {
            nekretnine.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(Izbornik.class.getName()).log(Level.SEVERE, null, ex);
        }
        nekretnine.show();
    }//GEN-LAST:event_AkcijaNekretnineActionPerformed

    private void AkcijaKlijentiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AkcijaKlijentiActionPerformed
        Klijenti klijenti = new Klijenti();
        jDesktopPane1.add(klijenti);
        try {
            klijenti.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(Izbornik.class.getName()).log(Level.SEVERE, null, ex);
        }
        klijenti.show();
    }//GEN-LAST:event_AkcijaKlijentiActionPerformed

    private void AkcijaPonudaPotraznjaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AkcijaPonudaPotraznjaActionPerformed
        PonudePotraznje ponudePotraznje = new PonudePotraznje();
        jDesktopPane1.add(ponudePotraznje);
        try {
            ponudePotraznje.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(Izbornik.class.getName()).log(Level.SEVERE, null, ex);
        }
        ponudePotraznje.show();
    }//GEN-LAST:event_AkcijaPonudaPotraznjaActionPerformed

    private void AkcijaOdjavaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AkcijaOdjavaActionPerformed
        dispose();
        new Autorizacija().setVisible(true);
    }//GEN-LAST:event_AkcijaOdjavaActionPerformed

    
    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/pictures/real_estate_icon.jpg")));
    }
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AkcijaKlijenti;
    private javax.swing.JButton AkcijaNekretnine;
    private javax.swing.JButton AkcijaOdjava;
    private javax.swing.JButton AkcijaPonudaPotraznja;
    private javax.swing.JButton akcijaAgenti;
    private javax.swing.JMenuItem akcijaIzlaz;
    private javax.swing.JLabel datum;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JMenu oProgramu;
    private javax.swing.JLabel pozadina;
    // End of variables declaration//GEN-END:variables

    
}
