/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edunova.view;

import edunova.controller.ObradaKlijent;
import edunova.controller.ObradaNekretnina;
import edunova.controller.ObradaPonudaPotraznja;
import edunova.model.Klijent;
import edunova.model.Nekretnina;
import edunova.model.PonudaPotraznja;
import java.awt.Color;
import java.awt.Component;
import java.io.FileInputStream;
import java.io.InputStream;
import java.math.BigDecimal;
import java.text.NumberFormat;
import java.text.ParseException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.DefaultListModel;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperExportManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.data.JRBeanCollectionDataSource;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;

/**
 *
 * @author Mario
 */
public class PonudePotraznje extends javax.swing.JInternalFrame {
    
    private ObradaPonudaPotraznja obradaPonudaPotraznja;
    private PonudaPotraznja odabranoPonudaPotraznja;
    private ObradaNekretnina obradaNekretnina;
    private Nekretnina odabranoNekretnina;
    private ObradaKlijent obradaKlijent;
    private Klijent odabranoKlijent;

    /**
     * Creates new form PonudePotraznje1
     */
    public PonudePotraznje() {
        initComponents();
        
        obradaPonudaPotraznja = new ObradaPonudaPotraznja();
        listaPonuda.setModel(new DefaultListModel<PonudaPotraznja>());
        setTitle("Ponuda/potražnja");

        obradaNekretnina = new ObradaNekretnina();
        obradaKlijent = new ObradaKlijent();

        kupnjaNekretnine.setSelected(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        akcijaTraziKlijenta = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaKlijent = new javax.swing.JList();
        uvjetKlijent = new javax.swing.JTextField();
        akcijaDodajNovuNekretninu = new javax.swing.JButton();
        akcijaDodajNovogKlijenta = new javax.swing.JButton();
        kupnjaNekretnine = new javax.swing.JCheckBox();
        prodajaNekretnine = new javax.swing.JCheckBox();
        jPanel1 = new javax.swing.JPanel();
        uvjetNekretnina = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaNekretnina = new javax.swing.JList();
        akcijaTraziNekretninu = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        akcijaUracunajProviziju = new javax.swing.JButton();
        provizija = new javax.swing.JTextField();
        datum = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cijenaSprovizijom = new javax.swing.JTextField();
        cijena = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        akcijaKreirajPonudu = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        akcijaTraziPonude = new javax.swing.JButton();
        UvjetPonudaPotraznja = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        listaPonuda = new javax.swing.JList();
        jPanel5 = new javax.swing.JPanel();
        akcijaObrisi = new javax.swing.JButton();
        akcijaPosalji = new javax.swing.JButton();
        akcijaGenerirajPDF = new javax.swing.JButton();
        akcijaOdustani = new javax.swing.JButton();

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Pretraga klijenata (* za sve)"));

        akcijaTraziKlijenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/Magnifier2.png"))); // NOI18N
        akcijaTraziKlijenta.setText("Traži klijenta");
        akcijaTraziKlijenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                akcijaTraziKlijentaActionPerformed(evt);
            }
        });

        listaKlijent.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listaKlijentValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(listaKlijent);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(uvjetKlijent, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(akcijaTraziKlijenta, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(uvjetKlijent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(akcijaTraziKlijenta))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        akcijaDodajNovuNekretninu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/Add_Blue.png"))); // NOI18N
        akcijaDodajNovuNekretninu.setText("Dodaj novo");
        akcijaDodajNovuNekretninu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                akcijaDodajNovuNekretninuActionPerformed(evt);
            }
        });

        akcijaDodajNovogKlijenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/Add_Blue.png"))); // NOI18N
        akcijaDodajNovogKlijenta.setText("Dodaj novo");
        akcijaDodajNovogKlijenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                akcijaDodajNovogKlijentaActionPerformed(evt);
            }
        });

        kupnjaNekretnine.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        kupnjaNekretnine.setText("Kupnja nekretnine");
        kupnjaNekretnine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kupnjaNekretnineActionPerformed(evt);
            }
        });

        prodajaNekretnine.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        prodajaNekretnine.setText("Prodaja nekretnine");
        prodajaNekretnine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prodajaNekretnineActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Pretraga nekretnina (* za sve)"));

        listaNekretnina.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listaNekretninaValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(listaNekretnina);

        akcijaTraziNekretninu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/Magnifier2.png"))); // NOI18N
        akcijaTraziNekretninu.setText("Traži nekretninu");
        akcijaTraziNekretninu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                akcijaTraziNekretninuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(uvjetNekretnina)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(akcijaTraziNekretninu)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(uvjetNekretnina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(akcijaTraziNekretninu))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/real_estate_picture.jpg"))); // NOI18N

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        akcijaUracunajProviziju.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/calculator.png"))); // NOI18N
        akcijaUracunajProviziju.setText("Uračunaj proviziju");
        akcijaUracunajProviziju.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                akcijaUracunajProvizijuActionPerformed(evt);
            }
        });

        jLabel5.setText("Provizija [%]");

        jLabel6.setText("Cijena s provizijom [eur]");

        jLabel8.setText("Datum");

        jLabel4.setText("Cijena [eur]");

        akcijaKreirajPonudu.setBackground(new java.awt.Color(0, 102, 255));
        akcijaKreirajPonudu.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        akcijaKreirajPonudu.setText("Kreiraj ponudu");
        akcijaKreirajPonudu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                akcijaKreirajPonuduActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(provizija))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(cijenaSprovizijom, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cijena, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(datum, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE))))
                .addContainerGap())
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(akcijaKreirajPonudu, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(akcijaUracunajProviziju, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cijena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(datum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cijenaSprovizijom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(provizija, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(akcijaUracunajProviziju)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(akcijaKreirajPonudu, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Pretraga ponuda (* za sve)"));

        akcijaTraziPonude.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/Magnifier2.png"))); // NOI18N
        akcijaTraziPonude.setText("Traži ponude");
        akcijaTraziPonude.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                akcijaTraziPonudeActionPerformed(evt);
            }
        });

        jScrollPane3.setViewportView(listaPonuda);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(UvjetPonudaPotraznja, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(akcijaTraziPonude, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 759, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UvjetPonudaPotraznja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(akcijaTraziPonude))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );

        akcijaObrisi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/DeleteRed.png"))); // NOI18N
        akcijaObrisi.setText("Obriši");
        akcijaObrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                akcijaObrisiActionPerformed(evt);
            }
        });

        akcijaPosalji.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/messages-new.png"))); // NOI18N
        akcijaPosalji.setText("Pošalji");
        akcijaPosalji.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                akcijaPosaljiActionPerformed(evt);
            }
        });

        akcijaGenerirajPDF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/pdf.png"))); // NOI18N
        akcijaGenerirajPDF.setText("PDF");
        akcijaGenerirajPDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                akcijaGenerirajPDFActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(akcijaObrisi, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(akcijaGenerirajPDF, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(akcijaPosalji, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(akcijaGenerirajPDF)
                    .addComponent(akcijaPosalji)
                    .addComponent(akcijaObrisi))
                .addContainerGap())
        );

        akcijaOdustani.setBackground(new java.awt.Color(51, 153, 255));
        akcijaOdustani.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/back.png"))); // NOI18N
        akcijaOdustani.setText("Nazad");
        akcijaOdustani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                akcijaOdustaniActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(akcijaOdustani, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(281, 281, 281)
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(kupnjaNekretnine)
                                .addGap(25, 25, 25)
                                .addComponent(prodajaNekretnine))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(akcijaDodajNovuNekretninu))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(akcijaDodajNovogKlijenta)
                                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(282, 282, 282)
                                .addComponent(jLabel7))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(prodajaNekretnine)
                            .addComponent(kupnjaNekretnine, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(akcijaDodajNovuNekretninu)
                            .addComponent(akcijaDodajNovogKlijenta)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(akcijaOdustani, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void akcijaTraziKlijentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_akcijaTraziKlijentaActionPerformed

        List<Klijent> klijenti = obradaKlijent.dohvati(uvjetKlijent.getText());

        DefaultListModel<Klijent> m = new DefaultListModel<>();
        for (Klijent klijent : klijenti) {
            m.addElement(klijent);
        }
        listaKlijent.setModel(m);
    }//GEN-LAST:event_akcijaTraziKlijentaActionPerformed

    private void listaKlijentValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listaKlijentValueChanged
        reset();
        odabranoKlijent = (Klijent) listaKlijent.getSelectedValue();
        if (odabranoKlijent == null) {
            return;
        }
        provizija.setText(String.valueOf(odabranoKlijent.getProvizija()));
    }//GEN-LAST:event_listaKlijentValueChanged

    private void akcijaDodajNovuNekretninuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_akcijaDodajNovuNekretninuActionPerformed
        new DodajNekretninu().setVisible(true);
    }//GEN-LAST:event_akcijaDodajNovuNekretninuActionPerformed

    private void akcijaDodajNovogKlijentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_akcijaDodajNovogKlijentaActionPerformed
        new DodajKlijenta().setVisible(true);
    }//GEN-LAST:event_akcijaDodajNovogKlijentaActionPerformed

    private void kupnjaNekretnineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kupnjaNekretnineActionPerformed
        if (kupnjaNekretnine.isSelected()) {
            prodajaNekretnine.setSelected(false);
            return;
        }

        if (!kupnjaNekretnine.isSelected()) {
            prodajaNekretnine.setSelected(true);

        }
    }//GEN-LAST:event_kupnjaNekretnineActionPerformed

    private void prodajaNekretnineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prodajaNekretnineActionPerformed
        if (prodajaNekretnine.isSelected()) {
            kupnjaNekretnine.setSelected(false);
            return;
        }

        if (!prodajaNekretnine.isSelected()) {
            kupnjaNekretnine.setSelected(true);

        }
    }//GEN-LAST:event_prodajaNekretnineActionPerformed

    private void listaNekretninaValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listaNekretninaValueChanged
        reset();
        odabranoNekretnina = (Nekretnina) listaNekretnina.getSelectedValue();
        if (odabranoNekretnina == null) {
            return;
        }
        cijena.setText(String.valueOf(odabranoNekretnina.getCijena()));
    }//GEN-LAST:event_listaNekretninaValueChanged

    private void akcijaTraziNekretninuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_akcijaTraziNekretninuActionPerformed
        cistiPolja();

        List<Nekretnina> entiteti = obradaNekretnina.dohvati(uvjetNekretnina.getText());
        DefaultListModel<Nekretnina> m = new DefaultListModel<>();
        for (Nekretnina e : entiteti) {
            m.addElement(e);
        }

        listaNekretnina.setModel(m);
    }//GEN-LAST:event_akcijaTraziNekretninuActionPerformed

    private void akcijaUracunajProvizijuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_akcijaUracunajProvizijuActionPerformed

        if (cijena.getText().trim().isEmpty()) {
            greska(cijena, "Obavezno cijena.");
            greska(provizija, "Obavezno provizija.");
            return;
        } else {
            Float c1 = new Float(cijena.getText());
            Float pro = new Float(provizija.getText());
            Float c2 = c1 * ((pro / 100) + 1);
            cijenaSprovizijom.setText(Float.toString(c2));

        }
    }//GEN-LAST:event_akcijaUracunajProvizijuActionPerformed

    private void akcijaKreirajPonuduActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_akcijaKreirajPonuduActionPerformed
        reset();

        if (cijena.getText().trim().isEmpty()) {
            greska(cijena, "Obavezno odabrati nekretninu");
            return;
        }
        
        try {
            NumberFormat.getInstance().parse(cijena.getText());
        } catch (ParseException e) {
            greska(cijena, "Mora biti broj");
            return;
        }

        if (provizija.getText().trim().isEmpty()) {
            greska(provizija, "Obavezno odabrati klijenta");
            return;
        }
        
        try {
            NumberFormat.getInstance().parse(provizija.getText());
        } catch (ParseException e) {
            greska(provizija, "Mora biti broj");
            return;
        }

        if (cijenaSprovizijom.getText().trim().isEmpty()) {
            greska(cijenaSprovizijom, "Obavezno uračunati proviziju");
            return;
        }
        
        try {
            NumberFormat.getInstance().parse(cijenaSprovizijom.getText());
        } catch (ParseException e) {
            greska(cijenaSprovizijom, "Mora biti broj");
            return;
        }

        if (odabranoNekretnina == null
            || listaNekretnina.getSelectedValuesList().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Prvo odaberite nekretninu", "Pogreška", JOptionPane.ERROR_MESSAGE);
            this.listaNekretnina.requestFocus();
            return;
        }

        if (odabranoKlijent == null
            || listaKlijent.getSelectedValuesList().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Prvo odaberite klijenta", "Pogreška", JOptionPane.ERROR_MESSAGE);
            this.listaKlijent.requestFocus();
            return;
        }
        
        if (datum.getCalendar() == null || datum.getCalendar().getTime() == null) {
            JOptionPane.showMessageDialog(rootPane, "Prvo odaberite datum", "Pogreška", JOptionPane.ERROR_MESSAGE);
            this.datum.requestFocus();
            return;
        }

        PonudaPotraznja pp = new PonudaPotraznja();

        pp.setNaziv(getTitle().trim());
        pp.setDatum(datum.getDate());
        pp.setCijenasprovizijom(new BigDecimal(cijenaSprovizijom.getText().trim()));
        pp.setKupnjanekretnine(kupnjaNekretnine.isSelected());
        pp.setProdajanekretnine(prodajaNekretnine.isSelected());
        pp.setKlijenti(odabranoKlijent);
        pp.setNekretnine(odabranoNekretnina);

        pp = obradaPonudaPotraznja.dodaj(pp);

        DefaultListModel<PonudaPotraznja> m = (DefaultListModel<PonudaPotraznja>) listaPonuda.getModel();
        m.addElement(pp);
    }//GEN-LAST:event_akcijaKreirajPonuduActionPerformed

    private void akcijaTraziPonudeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_akcijaTraziPonudeActionPerformed

        List<PonudaPotraznja> entiteti = obradaPonudaPotraznja.dohvatiPonudaPotraznja(UvjetPonudaPotraznja.getText());

        DefaultListModel<PonudaPotraznja> m = new DefaultListModel<>();
        for (PonudaPotraznja e : entiteti) {
            m.addElement(e);
        }

        listaPonuda.setModel(m);
    }//GEN-LAST:event_akcijaTraziPonudeActionPerformed

    private void akcijaObrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_akcijaObrisiActionPerformed
        odabranoPonudaPotraznja = (PonudaPotraznja) listaPonuda.getSelectedValue();
        if (odabranoPonudaPotraznja == null) {
            return;
        }
        if (JOptionPane.showConfirmDialog(getParent(), "Jeste li sigurni da želite obrisati: " + odabranoPonudaPotraznja.getNaziv() + " " + odabranoPonudaPotraznja.getSifra() + "?", "Brisanje ponude", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE) == JOptionPane.NO_OPTION) {
            return;
        }

        if (!obradaPonudaPotraznja.obrisi(odabranoPonudaPotraznja)) {
            return;
        }

        DefaultListModel<edunova.model.PonudaPotraznja> m = (DefaultListModel<edunova.model.PonudaPotraznja>) listaPonuda.getModel();
        m.removeElement(odabranoPonudaPotraznja);
        listaPonuda.repaint();
        cistiPolja();
    }//GEN-LAST:event_akcijaObrisiActionPerformed

    private void akcijaPosaljiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_akcijaPosaljiActionPerformed
        new Email().setVisible(true);
    }//GEN-LAST:event_akcijaPosaljiActionPerformed

    private void akcijaGenerirajPDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_akcijaGenerirajPDFActionPerformed
        odabranoPonudaPotraznja = (PonudaPotraznja) listaPonuda.getSelectedValue();

        if (odabranoPonudaPotraznja == null
            && listaPonuda.getSelectedValuesList().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Prvo odaberite stavku", "Pogreška", JOptionPane.ERROR_MESSAGE);
            this.listaPonuda.requestFocus();
            return;
        }

        try {
            InputStream inputStream = new FileInputStream("reports/MYreport.jrxml");

            List<PonudaPotraznja> l = obradaPonudaPotraznja.dohvatiPonudaPotraznja("");

            JRBeanCollectionDataSource beanColDataSource = new JRBeanCollectionDataSource(l);

            Map parameters = new HashMap();

            parameters.put("ponudapotraznja", odabranoPonudaPotraznja);
            parameters.put("klijent", odabranoPonudaPotraznja.getKlijenti());
            parameters.put("nekretnina", odabranoPonudaPotraznja.getNekretnine());

            JasperDesign jasperDesign = JRXmlLoader.load(inputStream);
            JasperReport jasperReport = JasperCompileManager.compileReport(jasperDesign);
            JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, parameters, beanColDataSource);
            String naziv = "d:/MYreport" + System.currentTimeMillis() + ".pdf";
            JasperExportManager.exportReportToPdfFile(jasperPrint, naziv);

            ProcessBuilder pb = new ProcessBuilder("cmd", "/C start " + naziv);
            pb.start();

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_akcijaGenerirajPDFActionPerformed

    private void akcijaOdustaniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_akcijaOdustaniActionPerformed
        dispose();
    }//GEN-LAST:event_akcijaOdustaniActionPerformed

    private void cistiPolja() {
        cijena.setText("");
        cijenaSprovizijom.setText("");

    }

    private void greska(JComponent komponenta, String obavijest) {
        komponenta.setBackground(Color.red);
        komponenta.requestFocus();
        komponenta.setToolTipText(obavijest);

    }

    private void reset() {

        for (Component c : this.getContentPane().getComponents()) {
            if (c instanceof JTextField) {
                JComponent jc = (JComponent) c;
                jc.setBackground(Color.white);
                jc.setToolTipText("");
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField UvjetPonudaPotraznja;
    private javax.swing.JButton akcijaDodajNovogKlijenta;
    private javax.swing.JButton akcijaDodajNovuNekretninu;
    private javax.swing.JButton akcijaGenerirajPDF;
    private javax.swing.JButton akcijaKreirajPonudu;
    private javax.swing.JButton akcijaObrisi;
    private javax.swing.JButton akcijaOdustani;
    private javax.swing.JButton akcijaPosalji;
    private javax.swing.JButton akcijaTraziKlijenta;
    private javax.swing.JButton akcijaTraziNekretninu;
    private javax.swing.JButton akcijaTraziPonude;
    private javax.swing.JButton akcijaUracunajProviziju;
    private javax.swing.JTextField cijena;
    private javax.swing.JTextField cijenaSprovizijom;
    private com.toedter.calendar.JDateChooser datum;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JCheckBox kupnjaNekretnine;
    private javax.swing.JList listaKlijent;
    private javax.swing.JList listaNekretnina;
    private javax.swing.JList listaPonuda;
    private javax.swing.JCheckBox prodajaNekretnine;
    private javax.swing.JTextField provizija;
    private javax.swing.JTextField uvjetKlijent;
    private javax.swing.JTextField uvjetNekretnina;
    // End of variables declaration//GEN-END:variables
}
